apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrofox-be-dev
  namespace: default
spec:
  selector:
    matchLabels:
      app: metrofox-be-dev
  template:
    metadata:
      labels:
        app: metrofox-be-dev
    spec:
      containers:
        - name: metrofox-be
          image: gcr.io/metrofox/metrofox-monolith:==BUILD_ID==
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATASOURCE_PASSWORD
              value: ==SPRING_DATASOURCE_PASSWORD==
        - name: greenmail
          image: greenmail/standalone:1.6.0
          ports:
            - containerPort: 3025
              protocol: TCP
            - containerPort: 3110
              protocol: TCP
            - containerPort: 3143
              protocol: TCP
            - containerPort: 3465
              protocol: TCP
            - containerPort: 3993
              protocol: TCP
            - containerPort: 3995
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Dgreenmail.startup.timeout=5000"
---
apiVersion: v1
kind: Service
metadata:
  name: metrofox-be-dev
spec:
  selector:
    app: metrofox-be-dev
  ports:
    - port: 80
      name: web
      protocol: TCP
      targetPort: 8080
    - port: 3025
      name: smtp
      protocol: TCP
      targetPort: 3025
    - port: 3110
      name: pop3
      protocol: TCP
      targetPort: 3110
    - port: 3143
      name: imap
      protocol: TCP
      targetPort: 3143
    - port: 3465
      name: smtps
      protocol: TCP
      targetPort: 3465
    - port: 3993
      name: imaps
      protocol: TCP
      targetPort: 3993
    - port: 3995
      name: pop3s
      protocol: TCP
      targetPort: 3995
  type: LoadBalancer
